import os

Import('env')

#extensions = ['*.cu', '*.cpp']
extensions = []

# gather sources in .
sources = env.Glob('cuda/testframework.cu')
for ext in extensions:
  sources.extend(env.Glob(ext))

# recursively glob sources from children
for ext in extensions:
  sources.extend(env.RecursiveGlob(ext, 'generic'))
  sources.extend(env.RecursiveGlob(ext, env['device_backend']))

# return the result to the parent
Return('sources')

